language: java
sudo: false # faster builds
install: true

jdk: openjdk16

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  - mvn compile exec:java -pl antlr

after_success:
  - bash <(curl -s https://codecov.io/bash)